services:
  postgres:
    image: 'postgres:latest'
    container_name: movie-rating-postgres
    environment:
      - 'POSTGRES_DB=movie-rating'
      - 'POSTGRES_PASSWORD=sky'
      - 'POSTGRES_USER=sky'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin
    container_name: movie-rating-zipkin
    ports:
      - '9411:9411'
volumes:
  postgres-data: