spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    contexts: dev,seed

logging:
  level:
    com.movierating: DEBUG
    org.springframework.web: DEBUG