name: CI Pipeline (Java 21 - Test & Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1️⃣ TEST JOB
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: |
          chmod +x mvnw || true
          ./mvnw clean test

  # 2️⃣ BUILD JOB
  build:
    name: Build and Verify Docker Image
    runs-on: ubuntu-latest
    needs: test  # <-- Runs only after tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR (skip tests since already run)
        run: |
          chmod +x mvnw || true
          ./mvnw clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t movie-rating-service:latest .

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Smoke test docker-compose stack
        run: |
          docker compose up -d
          echo "Waiting for app to start..."
          sleep 25
          docker ps
          echo "Checking logs..."
          docker logs movie-rating-service || true
          docker compose down -v
